# prompt-wide option
# Disable the newline at the start of the prompt
add_newline = false

# format

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[username]
disabled = false
style_root = "bold fg:red"
style_user = "bold fg:cyan"

[hostname]
disabled = false
style = "bold fg:green"
ssh_only = true
format = "[$hostname]($style) in"
# Linux
# îœ’
# Windows
# îœ
# mac/apple
# îœ‘

[directory]
disabled = false
style = "bold fg:bright-green"
# fish_style_pwd_dir_length = 1
format = "[î—¾ $path]($style)[$lock_symbol]($lock_style) "

[git_branch]
disabled = false
style = "bold fg:bright-blue"
symbol = "ï˜ "

[git_commit]
disabled = false
style = "bold bright-blue"

[git_state]
disabled = false
style = "bold bright-red"

[git_status]
disabled = false
style = "bold fg:red"
conflicted_count.enabled = true
modified_count.enabled = true
staged_count.enabled = true
show_sync_count = true

[dotnet]
disabled = false
# symbol = "î¿ "

[java]
disabled = false
# symbol = "îœ¸ "

[package]
disabled = false
# symbol = "îœž "

[nodejs]
disabled = false
# symbol = "îœ˜ "

[golang]
disabled = false
# symbol = "îœ¤ "

[python]
disabled = false
pyenv_version_name = true
# symbol = "îœ¼ "

[ruby]
disabled = false
# symbol = "îœ¹ "

[cmd_duration]
disabled = false
style = "bold fg:green"

[env_var]
disabled = true

[time]
disabled = false
# format = "ï€—[\\[$time\\]]($style)"
# format = "ðŸ•’[\\[$time\\]]($style)"
format = "â°[\\[$time\\]]($style)"
time_format = "%FT%T%:z"
# time_format = "%+"
utc_time_offset = "local"
style = "bold dimmed fg:white bg:blue"

# [battery]
# full_symbol = "ï•¸"
# charging_symbol = "ï–ƒ"
# discharging_symbol = "ï–‚"

[character]
disabled = false
success_symbol = " [\\$OK>](bold green)"
error_symbol = " [\\$NG>](bold red)"
vicmd_symbol = " [%VI>](bold blue)"
